// <auto-generated />
using System;
using DAOs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAOs.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20240607165327_Add Identity")]
    partial class AddIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateExpireRefreshToken")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isActive");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Class", b =>
                {
                    b.Property<string>("ClassId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ClassID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("StudentID");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("SubjectID");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("TutorID");

                    b.HasKey("ClassId")
                        .HasName("PK__Class__CB1927A0090BF352");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TutorId");

                    b.ToTable("Class", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Complaint", b =>
                {
                    b.Property<string>("ComplaintId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ComplaintID");

                    b.Property<DateOnly>("CreateDay")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("StudentID");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("TutorID");

                    b.HasKey("ComplaintId")
                        .HasName("PK__Complain__740D89AFCEF50736");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorId");

                    b.ToTable("Complaint", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Conversation", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ConversationID");

                    b.Property<DateOnly>("CreateDay")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ConversationId")
                        .HasName("PK__Conversa__C050D897C401235F");

                    b.ToTable("Conversation", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.ConversationAccount", b =>
                {
                    b.Property<string>("ConversationId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ConversationID");

                    b.Property<string>("AccountId")
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AccountID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("ConversationId", "AccountId")
                        .HasName("PK__Conversa__B31902CF056C16DA");

                    b.HasIndex("AccountId");

                    b.ToTable("Conversation_Account", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Feedback", b =>
                {
                    b.Property<string>("FeedbackId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("FeedbackID");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ClassID");

                    b.Property<DateOnly>("CreateDay")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("StudentID");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("TutorID");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__6A4BEDF65E258262");

                    b.HasIndex("ClassId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.FindTutorForm", b =>
                {
                    b.Property<string>("FormId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("FormID");

                    b.Property<DateOnly>("CreateDay")
                        .HasColumnType("date");

                    b.Property<string>("DescribeTutor")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("StudentID");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("SubjectID");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("TutorGender")
                        .HasColumnType("bit");

                    b.Property<string>("TypeOfDegree")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("FormId")
                        .HasName("PK__FindTuto__FB05B7BD12F4FFB4");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("FindTutorForm", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Grade", b =>
                {
                    b.Property<string>("GradeId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("GradeID");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("GradeId")
                        .HasName("PK__Grade__54F87A37CC152DE4");

                    b.ToTable("Grade", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Message", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("MessageID");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AccountID");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("ConversationID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Time")
                        .HasColumnType("date");

                    b.HasKey("MessageId")
                        .HasName("PK__Message__C87C037C2D324FDF");

                    b.HasIndex("AccountId");

                    b.HasIndex("ConversationId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Notification", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("NotificationID");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AccountID");

                    b.Property<DateOnly>("CreateDay")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E32FFBD5FC4");

                    b.HasIndex("AccountId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("RoleID");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE3A42B64DA9");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("StudentID");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AccountID");

                    b.Property<string>("SchoolName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("StudentId")
                        .HasName("PK__Student__32C52A79D012377F");

                    b.HasIndex("AccountId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Subject", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("SubjectID");

                    b.Property<string>("GradeId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("GradeID");

                    b.Property<string>("SubjectGroupId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("SubjectGroupID");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subject__AC1BA388537DD7A1");

                    b.HasIndex("GradeId");

                    b.HasIndex("SubjectGroupId");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.SubjectGroup", b =>
                {
                    b.Property<string>("SubjectGroupId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("SubjectGroupID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SubjectGroupId")
                        .HasName("PK__SubjectG__2F88B016AD652F27");

                    b.ToTable("SubjectGroup", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.SubjectTutor", b =>
                {
                    b.Property<string>("SubjectId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("SubjectID");

                    b.Property<string>("TutorId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("TutorID");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("SubjectId", "TutorId")
                        .HasName("PK__Subject___9B67D374BBB4AFD2");

                    b.HasIndex("TutorId");

                    b.ToTable("Subject_Tutor", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Transaction", b =>
                {
                    b.Property<string>("TransactionId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("TransactionID");

                    b.Property<DateOnly>("CreateDay")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<float>("TransactionMoney")
                        .HasColumnType("real");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("WalletID");

                    b.HasKey("TransactionId")
                        .HasName("PK__Transact__55433A4B61451DBE");

                    b.HasIndex("WalletId");

                    b.ToTable("Transaction", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Tutor", b =>
                {
                    b.Property<string>("TutorId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("TutorID");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AccountID");

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("CardID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Headline")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<float>("HourlyRate")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Photo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TypeOfDegree")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TutorId")
                        .HasName("PK__Tutor__77C70FC2A16C50DB");

                    b.HasIndex("AccountId");

                    b.ToTable("Tutor", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.TutorAd", b =>
                {
                    b.Property<string>("AdsId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("AdsID");

                    b.Property<DateOnly>("CreateDay")
                        .HasColumnType("date");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("TutorID");

                    b.Property<string>("Video")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("AdsId")
                        .HasName("PK__Tutor_Ad__46AAC65A5EF65941");

                    b.HasIndex("TutorId");

                    b.ToTable("Tutor_Ads", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Wallet", b =>
                {
                    b.Property<string>("WalletId")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("WalletID");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AccountID");

                    b.Property<float>("Balance")
                        .HasColumnType("real");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("BankNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreateDay")
                        .HasColumnType("date");

                    b.HasKey("WalletId")
                        .HasName("PK__Wallet__84D4F92E9F63180B");

                    b.HasIndex("AccountId");

                    b.ToTable("Wallet", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("BusinessObjects.Account", b =>
                {
                    b.HasOne("BusinessObjects.Role", null)
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("BusinessObjects.Class", b =>
                {
                    b.HasOne("BusinessObjects.Student", "Student")
                        .WithMany("Classes")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FKClass301112");

                    b.HasOne("BusinessObjects.Subject", "Subject")
                        .WithMany("Classes")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FKClass105998");

                    b.HasOne("BusinessObjects.Tutor", "Tutor")
                        .WithMany("Classes")
                        .HasForeignKey("TutorId")
                        .IsRequired()
                        .HasConstraintName("FKClass479452");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BusinessObjects.Complaint", b =>
                {
                    b.HasOne("BusinessObjects.Student", "Student")
                        .WithMany("Complaints")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FKComplaint416082");

                    b.HasOne("BusinessObjects.Tutor", "Tutor")
                        .WithMany("Complaints")
                        .HasForeignKey("TutorId")
                        .IsRequired()
                        .HasConstraintName("FKComplaint196647");

                    b.Navigation("Student");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BusinessObjects.ConversationAccount", b =>
                {
                    b.HasOne("BusinessObjects.Account", "Account")
                        .WithMany("ConversationAccounts")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FKConversati818528");

                    b.HasOne("BusinessObjects.Conversation", "Conversation")
                        .WithMany("ConversationAccounts")
                        .HasForeignKey("ConversationId")
                        .IsRequired()
                        .HasConstraintName("FKConversati872380");

                    b.Navigation("Account");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("BusinessObjects.Feedback", b =>
                {
                    b.HasOne("BusinessObjects.Class", "Class")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FKFeedback912586");

                    b.HasOne("BusinessObjects.Student", "Student")
                        .WithMany("Feedbacks")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FKFeedback348843");

                    b.HasOne("BusinessObjects.Tutor", "Tutor")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TutorId")
                        .IsRequired()
                        .HasConstraintName("FKFeedback431721");

                    b.Navigation("Class");

                    b.Navigation("Student");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BusinessObjects.FindTutorForm", b =>
                {
                    b.HasOne("BusinessObjects.Student", "Student")
                        .WithMany("FindTutorForms")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FKFindTutorF134374");

                    b.HasOne("BusinessObjects.Subject", "Subject")
                        .WithMany("FindTutorForms")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FKFindTutorF727263");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("BusinessObjects.Message", b =>
                {
                    b.HasOne("BusinessObjects.Account", "Account")
                        .WithMany("Messages")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FKMessage179454");

                    b.HasOne("BusinessObjects.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .IsRequired()
                        .HasConstraintName("FKMessage125602");

                    b.Navigation("Account");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("BusinessObjects.Notification", b =>
                {
                    b.HasOne("BusinessObjects.Account", "Account")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FKNotificati765224");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObjects.Student", b =>
                {
                    b.HasOne("BusinessObjects.Account", "Account")
                        .WithMany("Students")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FKStudent718314");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObjects.Subject", b =>
                {
                    b.HasOne("BusinessObjects.Grade", "Grade")
                        .WithMany("Subjects")
                        .HasForeignKey("GradeId")
                        .IsRequired()
                        .HasConstraintName("FKSubject866932");

                    b.HasOne("BusinessObjects.SubjectGroup", "SubjectGroup")
                        .WithMany("Subjects")
                        .HasForeignKey("SubjectGroupId")
                        .IsRequired()
                        .HasConstraintName("FKSubject340947");

                    b.Navigation("Grade");

                    b.Navigation("SubjectGroup");
                });

            modelBuilder.Entity("BusinessObjects.SubjectTutor", b =>
                {
                    b.HasOne("BusinessObjects.Subject", "Subject")
                        .WithMany("SubjectTutors")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FKSubject_Tu675031");

                    b.HasOne("BusinessObjects.Tutor", "Tutor")
                        .WithMany("SubjectTutors")
                        .HasForeignKey("TutorId")
                        .IsRequired()
                        .HasConstraintName("FKSubject_Tu3188");

                    b.Navigation("Subject");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BusinessObjects.Transaction", b =>
                {
                    b.HasOne("BusinessObjects.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .IsRequired()
                        .HasConstraintName("FKTransactio181260");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("BusinessObjects.Tutor", b =>
                {
                    b.HasOne("BusinessObjects.Account", "Account")
                        .WithMany("Tutors")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FKTutor387597");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObjects.TutorAd", b =>
                {
                    b.HasOne("BusinessObjects.Tutor", "Tutor")
                        .WithMany("TutorAds")
                        .HasForeignKey("TutorId")
                        .IsRequired()
                        .HasConstraintName("FKTutor_Ads572887");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BusinessObjects.Wallet", b =>
                {
                    b.HasOne("BusinessObjects.Account", "Account")
                        .WithMany("Wallets")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FKWallet115696");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BusinessObjects.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BusinessObjects.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjects.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BusinessObjects.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BusinessObjects.Account", b =>
                {
                    b.Navigation("ConversationAccounts");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");

                    b.Navigation("Students");

                    b.Navigation("Tutors");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("BusinessObjects.Class", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("BusinessObjects.Conversation", b =>
                {
                    b.Navigation("ConversationAccounts");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("BusinessObjects.Grade", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("BusinessObjects.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("BusinessObjects.Student", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Complaints");

                    b.Navigation("Feedbacks");

                    b.Navigation("FindTutorForms");
                });

            modelBuilder.Entity("BusinessObjects.Subject", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("FindTutorForms");

                    b.Navigation("SubjectTutors");
                });

            modelBuilder.Entity("BusinessObjects.SubjectGroup", b =>
                {
                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("BusinessObjects.Tutor", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Complaints");

                    b.Navigation("Feedbacks");

                    b.Navigation("SubjectTutors");

                    b.Navigation("TutorAds");
                });

            modelBuilder.Entity("BusinessObjects.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
